### ISSUE TITLE
SyntaxError: unknown: Unexpected token

### ISSUE THREAD

**Issue by DanielRamosAcosta** [SuperPaintman/babel-plugin-syntax-pipeline#1]
I have tried lots of things, and I don't understand why it doesn't work for me.

Here is the snippet I'm using. Is the same example from the `test` directory:

```javascript
const path = require('path')

require('babel-core').transform(`
      const res = user.name
        |> capitalize
        |> sayHello;
    `, {
  plugins: ['syntax-pipeline']
});
```

When I execute it I get this error:

```
/home/daniel/newTest/node_modules/babel-core/lib/transformation/file/index.js:590
      throw err;
      ^

SyntaxError: unknown: Unexpected token (3:9)
  1 | 
  2 |       const res = user.name
> 3 |         |> capitalize
    |          ^
  4 |         |> sayHello;
  5 |     
    at Parser.pp$5.raise (/home/daniel/newTest/node_modules/babylon/lib/index.js:4454:13)
    at Parser.pp.unexpected (/home/daniel/newTest/node_modules/babylon/lib/index.js:1761:8)
    at Parser.pp$3.parseExprAtom (/home/daniel/newTest/node_modules/babylon/lib/index.js:3750:12)
    at Parser.pp$3.parseExprSubscripts (/home/daniel/newTest/node_modules/babylon/lib/index.js:3494:19)
    at Parser.pp$3.parseMaybeUnary (/home/daniel/newTest/node_modules/babylon/lib/index.js:3474:19)
    at Parser.pp$3.parseExprOp (/home/daniel/newTest/node_modules/babylon/lib/index.js:3435:42)
    at Parser.pp$3.parseExprOps (/home/daniel/newTest/node_modules/babylon/lib/index.js:3408:17)
    at Parser.pp$3.parseMaybeConditional (/home/daniel/newTest/node_modules/babylon/lib/index.js:3381:19)
    at Parser.pp$3.parseMaybeAssign (/home/daniel/newTest/node_modules/babylon/lib/index.js:3344:19)
    at Parser.pp$1.parseVar (/home/daniel/newTest/node_modules/babylon/lib/index.js:2340:24)
```
Versions:

`node`: `v8.2.1`
`babel-core`: `^6.25.0`
`babel-plugin-syntax-pipeline`: `^0.1.0`

I have no idea why this isn't working, I have cloned this repo and the tests are working fine...

**Comment by plexigras** [comment]
https://github.com/SuperPaintman/babel-plugin-transform-pipeline
